services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_USER=hackathon
      - CLICKHOUSE_PASSWORD=hackathon
      - CLICKHOUSE_DB=hackathon
    volumes:
      - clickhouse_data:/var/lib/clickhouse/
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8123/ping"]
      interval: 30s
      timeout: 5s
      retries: 3

  clickhouse-client:
    image: clickhouse/clickhouse-client:latest
    container_name: clickhouse-client
    command: ['--host', 'clickhouse-server', '--user', 'hackathon', '--password', 'hackathon']
    depends_on:
      clickhouse-server:
        condition: service_healthy

volumes:
  clickhouse_data: